workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'main'

stages:
  - docker build
  - tests & linters

cache:
    paths:
      - ~/.cache/pip/
build:
  stage: docker build
  script:
    docker build -t kapibara/auth:$CI_COMMIT_SHORT_SHA .

tests:
  stage: tests & linters
  services:
    - postgres:15.3
  script:
    - docker run -e POSTGRES_SERVER=host.docker.internal:5432 kapibara/auth:$CI_COMMIT_SHORT_SHA pytest
    - pytest --cov --cov-report term --cov-report xml:coverage.xml --junit-xml=report.xml
    # to not fail a build if artifacts didn't get generated
    - touch coverage.xml report.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml

linters:
  stage: tests & linters
  script:
    - apt install git -y
    - pre-commit run -a

variables:
  PYTHONPATH: $CI_PROJECT_PATH
  POSTGRES_DB: "auth"
  POSTGRES_USER: "auth"
  POSTGRES_PASSWORD: "auth"
  POSTGRES_SERVER: postgres:5432

default:
  tags:
    - backend
    - kapibara
  image: python:3.11-slim-buster
  before_script:
    - apt update
    - apt install gcc -y
    - pip install -r requirements.txt
