version: "3"

services:
  kapibara-auth:
    build: .
    restart: unless-stopped
    container_name: kapibara-auth
    depends_on:
      - kapibara-auth-db
      - kapibara-redis
    env_file:
      - .env
    ports:
      - "3333:3333"
    volumes:
      - ./app:/app

  kapibara-auth-db:
    image: postgres:15.3
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "54322:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  kapibara-redis:
    image: redis:7.2.0-alpine3.18
    restart: unless-stopped

volumes:
  db-data:
