version: "3"

services:
  auth:
    image: auth:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3333:80"
    env_file:
      - .env
    environment:
      - CONFIG_PATH=/app/config.yaml
    volumes:
      - ./config.yaml:/app/config.yaml

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5431:5432