"""make user agent nullable

Revision ID: 90fe433f1eeb
Revises: 62cd9f0bd6e6
Create Date: 2023-08-25 13:48:15.786620

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import app

# revision identifiers, used by Alembic.
revision: str = "90fe433f1eeb"
down_revision: Union[str, None] = "62cd9f0bd6e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("usersession", "useragent", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("usersession", "useragent", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
