"""Added created_at

Revision ID: 62cd9f0bd6e6
Revises: 0d627c28d0ba
Create Date: 2023-08-24 14:11:50.855433

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import app

# revision identifiers, used by Alembic.
revision: str = "62cd9f0bd6e6"
down_revision: Union[str, None] = "0d627c28d0ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usersession",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usersession", "created_at")
    # ### end Alembic commands ###
